name: Auto Regenerate File Index

# Nightly and manual trigger workflow to re-generate docs/INDEX.md
# When the generator produces a change, open an automated PR with the update.

on:
  schedule:
    - cron: "0 3 * * *" # nightly at 03:00 UTC
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  regenerate-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24.x"
      - name: Ensure PNPM is available
        run: |
          corepack enable
          corepack prepare pnpm@9.30.0 --activate
      - name: Install dependencies (no frozen lockfile)
        run: pnpm -w install --no-frozen-lockfile
      - name: Generate docs/INDEX.md
        run: scripts/index/generate-file-index.sh --write
      - name: Show git status
        run: git status --porcelain
      - name: Create Pull Request if changes
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "chore: regenerate docs/INDEX.md"
          commit-message: "chore: regenerate docs/INDEX.md (auto)"
          branch: "auto/regenerate-index-${{ github.run_id }}"
          labels: "automation, infra"
          assignees: ""
          body: |
            This PR was created automatically by the CI to ensure the repository file index is up to date.

            The changes were generated by `scripts/index/generate-file-index.sh --write`.

            Please review and merge if appropriate.
