/**
 * E2E Tests for attendance API
 * Generated by Test Intelligence System
 *
 * Route: /api/attendance
 * Methods: GET, POST
 * Auth Required: true
 *
 * @generated
 */

import { describe, it, expect, beforeAll } from "vitest";
import { BASE_URL, checkServerHealth, safeFetch, serverAvailable } from "./setup";

describe("attendance API E2E Tests", () => {
  beforeAll(async () => {
    const isUp = await checkServerHealth();
    if (!isUp) {
      console.warn("⚠️ Server not available at", BASE_URL);
    }
  });

  describe("GET /api/attendance", () => {
    // Requires authentication

    it("should return 200 for valid request", async () => {
      const { response } = await safeFetch(`${BASE_URL}/api/attendance`);
      if (!serverAvailable || !response) {
        expect(true).toBe(true); // Skip gracefully
        return;
      }
      expect(response.status).toBe(401);
    });

    it("should return 401 without authentication", async () => {
      const { response } = await safeFetch(`${BASE_URL}/api/attendance`);
      if (!serverAvailable || !response) {
        expect(true).toBe(true); // Skip gracefully
        return;
      }
      expect(response.status).toBe(401);
    });
  });

  describe("POST /api/attendance", () => {
    // Requires authentication
    // Input: CreateAttendanceRecordSchema

    it("should return 400 for invalid input", async () => {
      const { response } = await safeFetch(`${BASE_URL}/api/attendance`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({}),
      });
      if (!serverAvailable || !response) {
        expect(true).toBe(true); // Skip gracefully
        return;
      }
      expect([400, 401, 422]).toContain(response.status);
    });

    it("should handle valid request", async () => {
      const validPayload = {
        orgId: "org-test",
        shiftId: "shift-test",
        scheduleId: "sched-test",
        staffUid: "user-test",
        scheduledStart: Date.now() + 60 * 60 * 1000,
        scheduledEnd: Date.now() + 2 * 60 * 60 * 1000,
      };

      const { response } = await safeFetch(`${BASE_URL}/api/attendance`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(validPayload),
      });
      if (!serverAvailable || !response) {
        expect(true).toBe(true); // Skip gracefully
        return;
      }

      // Expect success or auth required
      expect([200, 201, 401, 403]).toContain(response.status);
    });
  });
});
