/**
 * E2E Tests for onboarding-join-with-token API
 * Generated by Test Intelligence System
 *
 * Route: /api/onboarding/join-with-token
 * Methods: POST
 * Auth Required: true
 *
 * @generated
 */

import { describe, it, expect, beforeAll } from "vitest";
import { BASE_URL, checkServerHealth, safeFetch, serverAvailable } from "./setup";

describe("onboarding-join-with-token API E2E Tests", () => {
  beforeAll(async () => {
    const isUp = await checkServerHealth();
    if (!isUp) {
      console.warn("⚠️ Server not available at", BASE_URL);
    }
  });

  describe("POST /api/onboarding/join-with-token", () => {
    // Requires authentication

    it("should return 400 for invalid input", async () => {
      const { response } = await safeFetch(`${BASE_URL}/api/onboarding/join-with-token`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({}),
      });
      if (!serverAvailable || !response) {
        expect(true).toBe(true); // Skip gracefully
        return;
      }
      expect([400, 401, 422]).toContain(response.status);
    });

    it("should handle valid request", async () => {
      const validPayload = {
        token: "join-token-test",
      };

      const { response } = await safeFetch(`${BASE_URL}/api/onboarding/join-with-token`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(validPayload),
      });
      if (!serverAvailable || !response) {
        expect(true).toBe(true); // Skip gracefully
        return;
      }

      // Expect success or auth required
      expect([200, 201, 401, 403]).toContain(response.status);
    });
  });
});
