// [P1][INTEGRITY][SCHEMA] Shifts schema
// Tags: P1, INTEGRITY, SCHEMA, ZOD, SHIFTS
import { z } from "zod";

/**
 * Shift status lifecycle
 */
export const ShiftStatus = z.enum(["draft", "published", "in_progress", "completed", "cancelled"]);
export type ShiftStatus = z.infer<typeof ShiftStatus>;

/**
 * Shift assignment status
 */
export const AssignmentStatus = z.enum([
  "unassigned",
  "assigned",
  "confirmed",
  "declined",
  "no_show",
]);
export type AssignmentStatus = z.infer<typeof AssignmentStatus>;

/**
 * Individual shift assignment
 * @property {string} uid - The user ID of the assigned staff member.
 * @property {AssignmentStatus} [status=assigned] - The status of the assignment.
 * @property {number} assignedAt - The timestamp of when the assignment was made.
 * @property {string} assignedBy - The user ID of the person who made the assignment.
 * @property {number} [confirmedAt] - The timestamp of when the staff member confirmed the assignment.
 * @property {string} [notes] - Any notes related to this assignment.
 */
export const ShiftAssignmentSchema = z.object({
  uid: z.string().min(1, "User ID is required"),
  status: AssignmentStatus.default("assigned"),
  assignedAt: z.number().int().positive(),
  assignedBy: z.string().min(1),
  confirmedAt: z.number().int().positive().optional(),
  notes: z.string().max(500).optional(),
});
export type ShiftAssignment = z.infer<typeof ShiftAssignmentSchema>;

/**
 * Full Shift document schema
 * Firestore path: /shifts/{orgId}/{scheduleId}/{shiftId}
 * or /orgs/{orgId}/schedules/{scheduleId}/shifts/{shiftId}
 * @property {string} id - The unique identifier for the shift.
 * @property {string} orgId - The ID of the organization this shift belongs to.
 * @property {string} scheduleId - The ID of the schedule this shift is part of.
 * @property {string} positionId - The ID of the position this shift requires.
 * @property {string} [venueId] - The ID of the venue where this shift takes place.
 * @property {string} [zoneId] - The ID of the zone within the venue.
 * @property {number} startTime - The start time of the shift as a Unix timestamp in milliseconds.
 * @property {number} endTime - The end time of the shift as a Unix timestamp in milliseconds.
 * @property {ShiftStatus} [status=draft] - The current status of the shift.
 * @property {ShiftAssignment[]} [assignments] - A list of staff assignments for this shift.
 * @property {number} [requiredStaff=1] - The number of staff required for this shift.
 * @property {string} [notes] - General notes about the shift.
 * @property {number} [breakMinutes=0] - The duration of the break in minutes.
 * @property {boolean} [aiGenerated=false] - Flag indicating if the shift was generated by AI.
 * @property {number} [aiConfidence] - The AI's confidence score for this shift assignment.
 * @property {string} createdBy - The user ID of the user who created the shift.
 * @property {number} createdAt - The timestamp of when the shift was created.
 * @property {number} updatedAt - The timestamp of when the shift was last updated.
 */
export const ShiftSchema = z
  .object({
    id: z.string().min(1),
    orgId: z.string().min(1, "Organization ID is required"),
    scheduleId: z.string().min(1, "Schedule ID is required"),
    positionId: z.string().min(1, "Position ID is required"),
    venueId: z.string().optional(),
    zoneId: z.string().optional(),

    // Time boundaries (Unix timestamps in milliseconds)
    startTime: z.number().int().positive(),
    endTime: z.number().int().positive(),

    status: ShiftStatus.default("draft"),

    // Staffing
    assignments: z.array(ShiftAssignmentSchema).default([]),
    requiredStaff: z.number().int().positive().default(1),

    // Metadata
    notes: z.string().max(1000).optional(),
    breakMinutes: z.number().int().nonnegative().default(0),

    // AI metadata
    aiGenerated: z.boolean().default(false),
    aiConfidence: z.number().min(0).max(1).optional(),

    createdBy: z.string().min(1),
    createdAt: z.number().int().positive(),
    updatedAt: z.number().int().positive(),
  })
  .refine((data) => data.endTime > data.startTime, {
    message: "End time must be after start time",
    path: ["endTime"],
  });
export type Shift = z.infer<typeof ShiftSchema>;

/**
 * Schema for creating a new shift
 * Used in POST /api/shifts
 * @property {string} orgId - The ID of the organization this shift belongs to.
 * @property {string} scheduleId - The ID of the schedule this shift is part of.
 * @property {string} positionId - The ID of the position this shift requires.
 * @property {string} [venueId] - The ID of the venue where this shift takes place.
 * @property {string} [zoneId] - The ID of the zone within the venue.
 * @property {number} startTime - The start time of the shift as a Unix timestamp in milliseconds.
 * @property {number} endTime - The end time of the shift as a Unix timestamp in milliseconds.
 * @property {number} [requiredStaff=1] - The number of staff required for this shift.
 * @property {string} [notes] - General notes about the shift.
 * @property {number} [breakMinutes] - The duration of the break in minutes.
 */
export const CreateShiftSchema = z
  .object({
    orgId: z.string().min(1, "Organization ID is required"),
    scheduleId: z.string().min(1, "Schedule ID is required"),
    positionId: z.string().min(1, "Position ID is required"),
    venueId: z.string().optional(),
    zoneId: z.string().optional(),
    startTime: z.number().int().positive(),
    endTime: z.number().int().positive(),
    requiredStaff: z.number().int().positive().default(1),
    notes: z.string().max(1000).optional(),
    breakMinutes: z.number().int().nonnegative().optional(),
  })
  .refine((data) => data.endTime > data.startTime, {
    message: "End time must be after start time",
    path: ["endTime"],
  });
export type CreateShiftInput = z.infer<typeof CreateShiftSchema>;

/**
 * Schema for updating an existing shift
 * Used in PATCH /api/shifts/{id}
 * @property {string} [positionId] - The new position ID for the shift.
 * @property {string} [venueId] - The new venue ID for the shift.
 * @property {string} [zoneId] - The new zone ID for the shift.
 * @property {number} [startTime] - The new start time for the shift.
 * @property {number} [endTime] - The new end time for the shift.
 * @property {ShiftStatus} [status] - The new status for the shift.
 * @property {number} [requiredStaff] - The new number of required staff.
 * @property {string} [notes] - The new notes for the shift.
 * @property {number} [breakMinutes] - The new break duration in minutes.
 */
export const UpdateShiftSchema = z.object({
  positionId: z.string().min(1).optional(),
  venueId: z.string().optional(),
  zoneId: z.string().optional(),
  startTime: z.number().int().positive().optional(),
  endTime: z.number().int().positive().optional(),
  status: ShiftStatus.optional(),
  requiredStaff: z.number().int().positive().optional(),
  notes: z.string().max(1000).optional(),
  breakMinutes: z.number().int().nonnegative().optional(),
});
export type UpdateShiftInput = z.infer<typeof UpdateShiftSchema>;

/**
 * Schema for assigning staff to a shift
 * Used in POST /api/shifts/{id}/assign
 * @property {string} uid - The user ID of the staff member to assign.
 * @property {string} [notes] - Any notes related to this assignment.
 */
export const AssignShiftSchema = z.object({
  uid: z.string().min(1, "User ID is required"),
  notes: z.string().max(500).optional(),
});
export type AssignShiftInput = z.infer<typeof AssignShiftSchema>;

/**
 * Query parameters for listing shifts
 * @property {string} orgId - The ID of the organization to list shifts for.
 * @property {string} [scheduleId] - Filter shifts by schedule ID.
 * @property {string} [positionId] - Filter shifts by position ID.
 * @property {string} [venueId] - Filter shifts by venue ID.
 * @property {ShiftStatus} [status] - Filter shifts by status.
 * @property {number} [startAfter] - Filter for shifts that start after this Unix timestamp (in milliseconds).
 * @property {number} [startBefore] - Filter for shifts that start before this Unix timestamp (in milliseconds).
 * @property {string} [assignedTo] - Filter shifts assigned to a specific user ID.
 * @property {number} [limit=50] - The maximum number of shifts to return.
 * @property {string} [cursor] - The cursor for pagination.
 */
export const ListShiftsQuerySchema = z.object({
  orgId: z.string().min(1, "Organization ID is required"),
  scheduleId: z.string().optional(),
  positionId: z.string().optional(),
  venueId: z.string().optional(),
  status: ShiftStatus.optional(),
  startAfter: z.coerce.number().int().positive().optional(),
  startBefore: z.coerce.number().int().positive().optional(),
  assignedTo: z.string().optional(),
  limit: z.coerce.number().int().positive().max(100).default(50),
  cursor: z.string().optional(),
});
export type ListShiftsQuery = z.infer<typeof ListShiftsQuerySchema>;
