// [P0][APP][ENV] Config
// Tags: P0, APP, ENV
// [MEDIUM][INFRA][INDEX]
// Tags: index, codegen, config
// Centralized knobs for the file index generator.

export const EXCLUDES = [
  "_legacy/**",
  "docs/archive/**",
  "**/node_modules/**",
  "**/.pnpm/**",
  "**/dist/**",
  "**/coverage/**",
  "**/.next/**",
  "**/.vercel/**",
  "**/.turbo/**",
  "**/.cache/**",
  "**/*.log",
  "**/*.tmp",
];

export const CATEGORIES = [
  { name: "Apps", match: (p) => p.startsWith("apps/") },
  { name: "Packages", match: (p) => p.startsWith("packages/") },
  { name: "Services", match: (p) => p.startsWith("services/") },
  { name: "Docs", match: (p) => p.startsWith("docs/") },
  { name: "Scripts", match: (p) => p.startsWith("scripts/") || p.startsWith("tools/") },
  { name: "Tests", match: (p) => p.startsWith("tests/") || /(^|\/)__tests__\//.test(p) },
  {
    name: "CI / Config",
    match: (p) =>
      p.startsWith(".github/") ||
      /(^|\/)(tsconfig.*|eslint.*|vitest.*|jest.*|turbo\.json|pnpm-.*\.yaml|pnpm-workspace\.yaml|firebase.*\.json|firestore.*\.json|tailwind.*\.cjs|tailwind.*\.ts|postcss.*|cspell\.json|\.prettier.*|\.markdownlint\.json|\.mcp\.json|eslint\.config\.mjs|vitest\.config\.ts|jest\.config\.ts)$/i.test(
        p,
      ),
  },
  { name: "Root", match: (p) => !p.includes("/") && !p.startsWith(".github/") },
];

export const HEADER = `<!-- AUTOGENERATED: do not hand-edit. Use scripts/index/generate-file-index.mjs -->
# Repository File Index

This index is generated from tracked files (via \`git ls-files\`) with smart grouping and standard excludes.
To regenerate locally:
\`\`\`bash
node scripts/index/generate-file-index.mjs --write
\`\`\`
`;
