#!/usr/bin/env node
// [P0][DOCS][CODE] Synchronize Repomix reports into architecture index
// Tags: P0, DOCS, CODE, AUTOMATION

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const reportPath = path.resolve(__dirname, "../docs/architecture/repomix-ci.md");
const dashboardPath = path.resolve(__dirname, "../docs/architecture/repomix-dashboard.md");
const indexPath = path.resolve(__dirname, "../docs/architecture/_index.md");
const archDir = path.resolve(__dirname, "../docs/architecture");

// Ensure directory exists
if (!fs.existsSync(archDir)) {
  fs.mkdirSync(archDir, { recursive: true });
}

// Fallback to dashboard if CI report not found
const activePath = fs.existsSync(reportPath) ? reportPath : dashboardPath;

if (!fs.existsSync(activePath)) {
  console.error("⚠️ No Repomix report found. Run 'pnpm repomix' first.");
  process.exit(1);
}

const timestamp = new Date().toISOString();
const report = fs.readFileSync(activePath, "utf-8");

const header = `# 🧭 Fresh Schedules Architecture Overview

**Last updated:** \`${timestamp}\`

Below is the latest dependency map and module structure generated by Repomix CI automation.

---

## Summary

This document is **auto-generated** on every push and nightly via GitHub Actions.
For live reports, check the [GitHub Actions Artifacts](../../actions).

---

`;

const footer = `

---

**Generated by:** [Repomix](https://github.com/yamadashy/repomix) automation
**Updated:** ${timestamp}
`;

fs.writeFileSync(indexPath, `${header}\n${report}${footer}`);

console.log("✅ docs/architecture/_index.md updated successfully.");
