import fs from 'fs';
import path from 'path';

const TARGET_FILE = path.join(process.cwd(), 'docs/blocks/SCHEMA_CATALOG.md');

const content = `<!-- This file is generated by scripts/gen_schema_catalog.ts -->
# Schema Catalog

This is a placeholder for the schema catalog.
`;

fs.writeFileSync(TARGET_FILE, content);
console.log(`Generated ${TARGET_FILE}`);
